FROM node:16 as base

WORKDIR /home/app/landing-downgrade

ENV PATH /home/app/landing-downgrade/node_modules/.bin:$PATH

COPY package*.json ./
COPY .npmrc ./

RUN npm install --location=global npm@8.15.0
RUN npm install --location=global react-scripts
RUN npm install --legacy-peer-deps
RUN npm run types

COPY . .
